version: '2'
services:
  apache_with_php:
    build: .
    volumes:
    - ./src:/var/www/html/
    ports:
    - "80:80"
    - "443:443"
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"

