version: '2'
services:
  web:
    image: nginx
    ports:
      - "80:80"     # web HTTP
      - "443:443"   # web HTTPS
      - "9001:9000" # xdebug
    depends_on:
      - php
      - db
      - phpmyadmin
    links:
      - php
      - db
      - phpmyadmin
    #command: ["./wait-for-it.sh", "db:5432"
    volumes:
      - ./opt/limitlessv/nginx/conf.d:/etc/nginx/conf.d
      - ./opt/limitlessv/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/limitlessv/log/nginx:/var/log/nginx
      - ./apps:/var/www/html/
    networks:
      - <project_name>-network

  php:
    build: .
    working_dir: /var/www
    volumes:
      - ./apps:/var/www/html/
    networks:
    - <project_name>-network

  db:
    image: mariadb
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./opt/limitlessv/mariadb:/var/lib/mysql  # Note if you using MySQL and not mariadb change the local path
    networks:
      - <project_name>-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_SERVER: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    networks:
      - <project_name>-network

  redis:
    image: redis
    ports:
    - 6379
    networks:
    - <project_name>-network

  redis-session:
    image: redis
    ports:
    - 6379
    networks:
    - <project_name>-network

  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025
    networks:
    - <project_name>-network

networks:
  <project_name>-network:
    driver: bridge
